#index:
#    path: /
#    controller: App\Controller\DefaultController::index

simulation:
      path: /simulation
      controller: App\Controller\SimulationController::index
      defaults: 
          path: /simulation
          permanent: true