#index:
#    path: /
#    controller: App\Controller\DefaultController::index

simulation:
      path: /simulation
      controller: App\Controller\SimulationController::index
      defaults: 
          path: /simulation
          permanent: true


teinte:
      path: /teinte
      controller: App\Controller\TeinteController::index
      defaults: 
          path: /teinte
          permanent: true

account_order:
    path: '/compte/mes-commandes'
    controller: 'App\Controller\AccountOrderController::index'
    methods: ['GET', 'POST']
